name: testainers
description: Testainer is a powerful Dart plugin designed to streamline the management of containers for testing purposes.
version: 0.0.2
repository: https://github.com/edufolly/testainers

environment:
  sdk: ^3.0.0

dev_dependencies:
  # https://pub.dev/packages/coverage
  coverage: ^1.6.3

  # https://pub.dev/packages/http
  http: ^1.1.0

  # https://pub.dev/packages/lints
  lints: ^2.1.0

  # https://pub.dev/packages/markdown
  markdown: ^7.1.0

  # https://pub.dev/packages/test
  test: ^1.24.0
