name: testainers
description: Testainer is a powerful Dart plugin designed to streamline the management of containers for testing purposes.
version: 0.0.1
repository: https://github.com/edufolly/testainers

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
